# Generated by Django 2.0.8 on 2019-01-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={},
        ),
        migrations.AlterModelTable(
            name='post',
            table='user_post',
        ),
        migrations.AlterModelTable(
            name='postlike',
            table='user_post_like',
        ),
    ]
