# Generated by Django 2.0.8 on 2019-01-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190105_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts'
            },
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={
                'verbose_name': 'Post Like',
                'verbose_name_plural': 'Post Likes'
            },
        ),
    ]
