# Generated by Django 2.0.8 on 2019-01-03 21:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20190103_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={
                'verbose_name': 'user post',
                'verbose_name_plural': 'user posts'
            },
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={
                'verbose_name': 'user post like',
                'verbose_name_plural': 'user post likes'
            },
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post')},
        ),
    ]
