# Generated by Django 2.0.8 on 2019-01-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190103_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={
                'verbose_name': 'User Post',
                'verbose_name_plural': 'User Posts'
            },
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={
                'verbose_name': 'User Post Like',
                'verbose_name_plural': 'User Post Likes'
            },
        ),
    ]
